const readonly = 'readonly';

export default [
  {
    ignores: [
      'node_modules/**',
      'artifacts/**',
      'graphify-out/**'
    ]
  },
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        AbortController: readonly,
        console: readonly,
        chrome: readonly,
        document: readonly,
        window: readonly,
        location: readonly,
        navigator: readonly,
        MutationObserver: readonly,
        DOMParser: readonly,
        Element: readonly,
        Event: readonly,
        MouseEvent: readonly,
        HTMLAnchorElement: readonly,
        Image: readonly,
        Blob: readonly,
        Headers: readonly,
        ReadableStream: readonly,
        TextDecoder: readonly,
        TextEncoder: readonly,
        URL: readonly,
        URLSearchParams: readonly,
        fetch: readonly,
        getComputedStyle: readonly,
        queueMicrotask: readonly,
        requestAnimationFrame: readonly,
        cancelAnimationFrame: readonly,
        setTimeout: readonly,
        clearTimeout: readonly,
        setInterval: readonly,
        clearInterval: readonly,
        module: readonly,
        require: readonly,
        process: readonly,
        Buffer: readonly,
        __dirname: readonly,
        global: readonly,
        structuredClone: readonly,
        describe: readonly,
        test: readonly,
        it: readonly,
        expect: readonly,
        beforeEach: readonly,
        afterEach: readonly,
        beforeAll: readonly,
        afterAll: readonly,
        jest: readonly
      }
    },
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-obj-calls': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unreachable-loop': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error'
    }
  },
  {
    files: ['**/*.cjs'],
    languageOptions: { sourceType: 'commonjs' }
  }
];
